# Generated by Django 4.0.6 on 2023-02-28 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_facebookusers_remove_post_pic_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookusers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookusers',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facebookusers',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
